### ISSUE TITLE
TypeError while importing editframe 

### ISSUE THREAD

**Issue by bhargavmungara** [editframe/editframe-js#127]
Was trying out editframe and when i imported it was showing TypeError.

Attached the images of the error and code 
<img width="1440" alt="Screenshot 2022-12-01 at 1 10 01 PM" src="https://user-images.githubusercontent.com/59245935/204994406-e2d33852-d44e-413a-afe8-3f479b356753.png">
<img width="1438" alt="Screenshot 2022-12-01 at 1 10 07 PM" src="https://user-images.githubusercontent.com/59245935/204994453-002b0132-96b3-477e-bf4e-0bd2b59334a0.png">

**Comment by bhargavmungara** [comment]
Sorry, attached wrong code image.

The below is correct image of the code and the error was same

<img width="1440" alt="Screenshot 2022-12-01 at 1 12 13 PM" src="https://user-images.githubusercontent.com/59245935/204994778-5ca95e66-3f7b-4cd6-9842-9fcbc34e31a3.png">

**Comment by IliasHad** [comment]
@bhargavmungara can you please sepcify the Node , OS and SDK version you´re using ?
